package com.wang.mac.cicadatravels.model.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COUNTRY_BEAN".
 */
public class CountryBean {

    private Long id;
    private String countryName;

    public CountryBean() {
    }

    public CountryBean(Long id) {
        this.id = id;
    }

    public CountryBean(Long id, String countryName) {
        this.id = id;
        this.countryName = countryName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCountryName() {
        return countryName;
    }

    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

}
