package com.wang.mac.cicadatravels.model.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.wang.mac.cicadatravels.model.db.CountryBean;

import com.wang.mac.cicadatravels.model.db.CountryBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig countryBeanDaoConfig;

    private final CountryBeanDao countryBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        countryBeanDaoConfig = daoConfigMap.get(CountryBeanDao.class).clone();
        countryBeanDaoConfig.initIdentityScope(type);

        countryBeanDao = new CountryBeanDao(countryBeanDaoConfig, this);

        registerDao(CountryBean.class, countryBeanDao);
    }
    
    public void clear() {
        countryBeanDaoConfig.getIdentityScope().clear();
    }

    public CountryBeanDao getCountryBeanDao() {
        return countryBeanDao;
    }

}
